name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      # test the current commit in integration testing
      uses: ${{ github.repository }}@${{ github.sha }}
      with:
        name: ${{ secrets.DOCKER_REPOSITORY }}
        # name: lgohr/publish-docker-github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
